### ISSUE TITLE
Issue-Add new dependency review workflow

Added workflow to CI/CD workflows

### ISSUE THREAD

**Issue by lind0118** [lind0118/gpd-backend#14]
Automated Review Comments
Issues in .github/workflows/dependency-review.yml:
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
Issues in package-lock.json:
  - (7, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (52, 'Line exceeds 80 characters')
  - (58, 'Hardcoded string found')
  - (59, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (60, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Line exceeds 80 characters')
  - (65, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (70, 'Line exceeds 80 characters')
  - (75, 'Hardcoded string found')
  - (76, 'Line exceeds 80 characters')
  - (76, 'Hardcoded string found')
  - (77, 'Line exceeds 80 characters')
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (85, 'Line exceeds 80 characters')
  - (85, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (93, 'Line exceeds 80 characters')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (108, 'Line exceeds 80 characters')
  - (108, 'Hardcoded string found')
Issues in package.json:
  - (7, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
