### ISSUE TITLE
Issue-Implement CRUD operations for Template (#13)

* Full resource creation with CRUD options for templates

* DTO files moved to models/template folder

* Updated DTOs for Template: CreateTemplateDto and UpdateTemplateDto

* Add CRUD logic in Template service file

* Added documentation to the CRUD fot the templates in the service file

* Updated the CRUD for the templates in the controller file

* Added documentation to CRUD for templates in controller file

* Added prism service in module file

* The CRUD logic of the service file was modified

* The CRUD logic of the controller file was modified

* Updated the method to create a template in the service file

* Changed the documentation for the controller and service files

* Added logic to validate if foreign keys exist in the service file

### ISSUE THREAD

**Issue by lind0118** [lind0118/gpd-backend#20]
Automated Review Comments
Issues in package-lock.json:
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
Issues in src/models/template/create-template.dto.ts:
  - (3, 'Hardcoded string found')
Issues in src/templates/templates.controller.spec.ts:
  - (6, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
Issues in src/templates/templates.controller.ts:
  - (16, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (52, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
Issues in src/templates/templates.service.spec.ts:
  - (5, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in src/templates/templates.service.ts:
  - (98, 'Hardcoded string found')

**Comment by williamddobson3** [comment]
I got it.
