### ISSUE TITLE
Issue-Added pr template (#14)

added pull request template

### ISSUE THREAD

**Issue by lind0118** [lind0118/gpd-backend#22]
Automated Review Comments
Issues in .github/PULL_REQUEST_TEMPLATE/pull_request.md:
  - (3, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')

**Comment by stevesjones813** [comment]
I got it.
