### ISSUE TITLE
Issue-Added code analize action CI

### ISSUE THREAD

**Issue by lind0118** [lind0118/gpd-backend#6]
Automated Review Comments
Issues in .github/workflows/codeql.yml:
  - (13, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (69, 'Line exceeds 80 characters')
  - (70, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (76, 'Hardcoded string found')
  - (77, 'Line exceeds 80 characters')
  - (77, 'Hardcoded string found')
  - (80, 'Line exceeds 80 characters')
  - (81, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (85, 'Line exceeds 80 characters')
  - (87, 'Hardcoded string found')
  - (88, 'Hardcoded string found')

**Comment by williamddobson3** [comment]
I got it.
